language: ruby
rvm:
- 2.2.0
deploy:
  provider: heroku
  api_key:
    secure: VuSjq1On/HdYNQdkJZLK4kWbkUjMiKhMAj59MgaoOf/mWT5CqYVJ8SolPhsaVXpdcviXHL2z9LpbBwCNtP6K3FIUyhWgKLFBA+NfgJl6MWBcNovKjwjlbRM31w0lGJ9ln2gQT5k76PftieS/l8uKbNxMpS5Rxphbnk8rp+rBGkI=
  app: bobotonslack
  on:
    repo: r7kamura/bobot
