source "https://rubygems.org"

gem "pry"
gem "rake"
gem "ruboty", github: 'sorah/ruboty', ref: 'cant-compare-boolean'
gem "ruboty-alias"
gem "ruboty-cron"
gem "ruboty-github"
gem "ruboty-google_image"
gem "ruboty-japan_weather"
gem "ruboty-lgtm"
gem "ruboty-redis"
gem "ruboty-slack"
gem "ruboty-syoboi_calendar"
gem "ruboty-scorekeeper"
