source "https://rubygems.org"

gem "pry"
gem "rake"
gem "ruboty"
gem "ruboty-alias"
gem "ruboty-attendance"
gem "ruboty-cron"
gem "ruboty-github"
gem "ruboty-google_image"
gem "ruboty-hitozuma"
gem "ruboty-imascg", github: 'sorah/ruboty-imascg'
gem "ruboty-imasml", github: 'sorah/ruboty-imasml'
gem "ruboty-japan_weather"
gem "ruboty-lgtm"
gem "ruboty-redis"
gem "ruboty-scorekeeper"
gem "ruboty-slack"
gem "ruboty-syoboi_calendar"
gem "ruboty-tumblr_image"
gem "ruboty-zoi", "~> 1.1.0"
